-- ============================================================================
-- SISTEMA INTEGRAL DE INVENTARIO + PRODUCCIÓN + SALIDA AUTOMÁTICA POR VENTA
-- Proyecto: Pollodonaconcha
-- Ejecutar completo en Supabase SQL Editor
-- ============================================================================

create extension if not exists pgcrypto;

-- ============================================================================
-- 1) TABLAS BASE
-- ============================================================================

create table if not exists public.insumos (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  categoria text not null default 'general',
  unidad text not null default 'unidad',
  stock_actual numeric(14,4) not null default 0,
  stock_minimo numeric(14,4) not null default 0,
  costo_unitario numeric(14,4) not null default 0,
  proveedor text,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stock_productos (
  id uuid primary key default gen_random_uuid(),
  producto_id uuid not null references public.productos(id) on delete cascade,
  stock_actual numeric(14,4) not null default 0,
  stock_minimo numeric(14,4) not null default 0,
  costo_promedio numeric(14,4) not null default 0,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint stock_productos_producto_id_key unique (producto_id)
);

create table if not exists public.inventario_config_productos (
  id uuid primary key default gen_random_uuid(),
  producto_id uuid not null references public.productos(id) on delete cascade,
  controla_inventario boolean not null default true,
  modo_consumo text not null default 'sin_control',
  permite_stock_negativo boolean not null default false,
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint inventario_config_producto_key unique (producto_id),
  constraint inventario_config_modo_check check (modo_consumo in ('receta', 'stock_producto', 'sin_control'))
);

create table if not exists public.recetas (
  id uuid primary key default gen_random_uuid(),
  producto_id uuid not null references public.productos(id) on delete cascade,
  nombre text not null,
  descripcion text,
  rendimiento numeric(14,4) not null default 1,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint recetas_producto_key unique (producto_id),
  constraint recetas_rendimiento_check check (rendimiento > 0)
);

create table if not exists public.recetas_detalle (
  id uuid primary key default gen_random_uuid(),
  receta_id uuid not null references public.recetas(id) on delete cascade,
  insumo_id uuid not null references public.insumos(id) on delete restrict,
  cantidad numeric(14,4) not null,
  unidad text not null default 'unidad',
  created_at timestamptz not null default now(),
  constraint recetas_detalle_cantidad_check check (cantidad > 0)
);

create table if not exists public.ordenes_produccion (
  id uuid primary key default gen_random_uuid(),
  numero_orden bigint generated by default as identity,
  producto_id uuid references public.productos(id) on delete set null,
  fecha date not null default current_date,
  estado text not null default 'completada',
  cantidad_producida numeric(14,4) not null default 0,
  notas text,
  cajero text,
  cajero_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ordenes_produccion_estado_check check (estado in ('borrador', 'en_proceso', 'completada', 'cancelada'))
);

create table if not exists public.ordenes_produccion_detalle (
  id uuid primary key default gen_random_uuid(),
  orden_id uuid not null references public.ordenes_produccion(id) on delete cascade,
  tipo text not null,
  producto_id uuid references public.productos(id) on delete set null,
  insumo_id uuid references public.insumos(id) on delete set null,
  cantidad numeric(14,4) not null,
  costo_unitario numeric(14,4) not null default 0,
  created_at timestamptz not null default now(),
  constraint ordenes_produccion_detalle_tipo_check check (tipo in ('consumo_insumo', 'producto_terminado')),
  constraint ordenes_produccion_detalle_cantidad_check check (cantidad > 0)
);

create table if not exists public.movimientos_inventario (
  id uuid primary key default gen_random_uuid(),
  item_tipo text not null,
  tipo text not null,
  referencia_tipo text,
  referencia_id text,
  insumo_id uuid references public.insumos(id) on delete set null,
  producto_id uuid references public.productos(id) on delete set null,
  cantidad numeric(14,4) not null,
  saldo_resultante numeric(14,4),
  costo_unitario numeric(14,4) not null default 0,
  nota text,
  cajero text,
  cajero_id text,
  created_at timestamptz not null default now(),
  constraint movimientos_item_tipo_check check (item_tipo in ('insumo', 'producto')),
  constraint movimientos_tipo_check check (
    tipo in (
      'entrada',
      'salida',
      'ajuste_positivo',
      'ajuste_negativo',
      'venta',
      'produccion_entrada',
      'produccion_salida'
    )
  )
);

comment on table public.insumos is 'Materias primas, empaques e ingredientes.';
comment on table public.stock_productos is 'Stock de productos terminados listos para vender.';
comment on table public.inventario_config_productos is 'Define cómo afecta una venta al inventario por producto.';
comment on table public.recetas is 'Receta maestra por producto de venta.';
comment on table public.recetas_detalle is 'Insumos requeridos por receta.';
comment on table public.ordenes_produccion is 'Lotes/producciones terminadas.';
comment on table public.movimientos_inventario is 'Kardex auditado de entradas, salidas, ventas y producción.';

-- ============================================================================
-- 2) ÍNDICES
-- ============================================================================

create index if not exists idx_insumos_nombre on public.insumos(nombre);
create index if not exists idx_insumos_categoria on public.insumos(categoria);
create index if not exists idx_stock_productos_producto on public.stock_productos(producto_id);
create index if not exists idx_recetas_producto on public.recetas(producto_id);
create index if not exists idx_recetas_detalle_receta on public.recetas_detalle(receta_id);
create index if not exists idx_movimientos_created_at on public.movimientos_inventario(created_at desc);
create index if not exists idx_movimientos_referencia on public.movimientos_inventario(referencia_tipo, referencia_id);
create index if not exists idx_ordenes_producto on public.ordenes_produccion(producto_id);

-- ============================================================================
-- 3) UPDATED_AT AUTOMÁTICO
-- ============================================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_insumos_updated_at on public.insumos;
create trigger trg_insumos_updated_at
before update on public.insumos
for each row execute function public.set_updated_at();

drop trigger if exists trg_stock_productos_updated_at on public.stock_productos;
create trigger trg_stock_productos_updated_at
before update on public.stock_productos
for each row execute function public.set_updated_at();

drop trigger if exists trg_inventario_config_updated_at on public.inventario_config_productos;
create trigger trg_inventario_config_updated_at
before update on public.inventario_config_productos
for each row execute function public.set_updated_at();

drop trigger if exists trg_recetas_updated_at on public.recetas;
create trigger trg_recetas_updated_at
before update on public.recetas
for each row execute function public.set_updated_at();

drop trigger if exists trg_ordenes_produccion_updated_at on public.ordenes_produccion;
create trigger trg_ordenes_produccion_updated_at
before update on public.ordenes_produccion
for each row execute function public.set_updated_at();

-- ============================================================================
-- 4) FUNCIÓN CENTRAL: REGISTRAR MOVIMIENTOS MANUALES O AUTOMÁTICOS
--    p_modo_estricto = true  → bloquea stock negativo (uso manual/producción)
--    p_modo_estricto = false → permite stock negativo, solo logea (uso en trigger de venta)
-- ============================================================================

create or replace function public.registrar_movimiento_inventario(
  p_item_tipo        text,
  p_item_id          uuid,
  p_tipo_movimiento  text,
  p_cantidad         numeric,
  p_costo_unitario   numeric  default 0,
  p_referencia_tipo  text     default null,
  p_referencia_id    text     default null,
  p_nota             text     default null,
  p_cajero           text     default null,
  p_cajero_id        text     default null,
  p_modo_estricto    boolean  default true
)
returns uuid
language plpgsql
as $$
declare
  v_delta          numeric(14,4);
  v_saldo          numeric(14,4);
  v_movimiento_id  uuid := gen_random_uuid();
  v_perm_stock_neg boolean := false;
begin
  if p_cantidad is null or p_cantidad <= 0 then
    raise exception 'La cantidad debe ser mayor a cero';
  end if;

  if p_item_tipo not in ('insumo', 'producto') then
    raise exception 'item_tipo inválido: %', p_item_tipo;
  end if;

  if p_tipo_movimiento not in (
    'entrada', 'salida', 'ajuste_positivo', 'ajuste_negativo',
    'venta', 'produccion_entrada', 'produccion_salida'
  ) then
    raise exception 'tipo_movimiento inválido: %', p_tipo_movimiento;
  end if;

  v_delta := case
    when p_tipo_movimiento in ('entrada', 'ajuste_positivo', 'produccion_entrada') then p_cantidad
    else p_cantidad * -1
  end;

  if p_item_tipo = 'insumo' then
    update public.insumos
       set stock_actual = stock_actual + v_delta,
           costo_unitario = case when p_costo_unitario > 0 then p_costo_unitario else costo_unitario end,
           updated_at = now()
     where id = p_item_id
     returning stock_actual into v_saldo;

    if not found then
      raise exception 'El insumo % no existe', p_item_id;
    end if;

    if p_modo_estricto and v_saldo < 0 then
      raise exception 'Stock insuficiente del insumo %. Saldo: %', p_item_id, v_saldo;
    end if;

    insert into public.movimientos_inventario (
      id, item_tipo, tipo, referencia_tipo, referencia_id, insumo_id,
      cantidad, saldo_resultante, costo_unitario, nota, cajero, cajero_id
    ) values (
      v_movimiento_id, 'insumo', p_tipo_movimiento, p_referencia_tipo, p_referencia_id, p_item_id,
      p_cantidad, v_saldo, coalesce(p_costo_unitario, 0), p_nota, p_cajero, p_cajero_id
    );

  else
    select coalesce(permite_stock_negativo, false)
      into v_perm_stock_neg
      from public.inventario_config_productos
     where producto_id = p_item_id;

    if exists (select 1 from public.stock_productos where producto_id = p_item_id) then
      update public.stock_productos
         set stock_actual = stock_actual + v_delta,
             costo_promedio = case
               when p_costo_unitario > 0 then p_costo_unitario
               else costo_promedio
             end,
             updated_at = now()
       where producto_id = p_item_id
       returning stock_actual into v_saldo;
    else
      if v_delta < 0 and not v_perm_stock_neg and p_modo_estricto then
        raise exception 'Stock insuficiente del producto % (sin fila en stock_productos)', p_item_id;
      end if;
      insert into public.stock_productos (producto_id, stock_actual, costo_promedio)
      values (p_item_id, greatest(v_delta, 0), coalesce(p_costo_unitario, 0))
      returning stock_actual into v_saldo;
    end if;

    if p_modo_estricto and not v_perm_stock_neg and v_saldo < 0 then
      raise exception 'Stock insuficiente del producto %. Saldo: %', p_item_id, v_saldo;
    end if;

    insert into public.movimientos_inventario (
      id, item_tipo, tipo, referencia_tipo, referencia_id, producto_id,
      cantidad, saldo_resultante, costo_unitario, nota, cajero, cajero_id
    ) values (
      v_movimiento_id, 'producto', p_tipo_movimiento, p_referencia_tipo, p_referencia_id, p_item_id,
      p_cantidad, v_saldo, coalesce(p_costo_unitario, 0), p_nota, p_cajero, p_cajero_id
    );
  end if;

  return v_movimiento_id;
end;
$$;

-- ============================================================================
-- 5) PRODUCCIÓN DESDE RECETA
--    Consume insumos y sube stock del producto terminado.
-- ============================================================================

create or replace function public.registrar_produccion_desde_receta(
  p_producto_id uuid,
  p_cantidad numeric,
  p_nota text default null,
  p_cajero text default null,
  p_cajero_id text default null
)
returns uuid
language plpgsql
as $$
declare
  v_receta record;
  v_detalle record;
  v_factor numeric(14,6);
  v_consumo numeric(14,4);
  v_orden_id uuid;
  v_costo numeric(14,4);
begin
  if p_cantidad is null or p_cantidad <= 0 then
    raise exception 'La cantidad a producir debe ser mayor a cero';
  end if;

  select r.id, r.rendimiento, r.descripcion
    into v_receta
    from public.recetas r
   where r.producto_id = p_producto_id
     and r.activo = true;

  if not found then
    raise exception 'No existe una receta activa para el producto %', p_producto_id;
  end if;

  v_factor := p_cantidad / greatest(v_receta.rendimiento, 1);

  -- Validar stock antes de procesar
  for v_detalle in
    select rd.insumo_id, rd.cantidad, i.stock_actual, coalesce(i.costo_unitario, 0) as costo_unitario
      from public.recetas_detalle rd
      join public.insumos i on i.id = rd.insumo_id
     where rd.receta_id = v_receta.id
  loop
    v_consumo := v_detalle.cantidad * v_factor;
  end loop;

  for v_detalle in
    select rd.insumo_id, rd.cantidad, i.stock_actual, coalesce(i.costo_unitario, 0) as costo_unitario
      from public.recetas_detalle rd
      join public.insumos i on i.id = rd.insumo_id
     where rd.receta_id = v_receta.id
  loop
    v_consumo := v_detalle.cantidad * v_factor;
    if v_detalle.stock_actual < v_consumo then
      raise exception 'Stock insuficiente del insumo % para producir % unidades', v_detalle.insumo_id, p_cantidad;
    end if;
  end loop;

  insert into public.ordenes_produccion (
    producto_id, fecha, estado, cantidad_producida, notas, cajero, cajero_id
  ) values (
    p_producto_id, current_date, 'completada', p_cantidad, p_nota, p_cajero, p_cajero_id
  )
  returning id into v_orden_id;

  for v_detalle in
    select rd.insumo_id, rd.cantidad, coalesce(rd.unidad, i.unidad) as unidad, coalesce(i.costo_unitario, 0) as costo_unitario
      from public.recetas_detalle rd
      join public.insumos i on i.id = rd.insumo_id
     where rd.receta_id = v_receta.id
  loop
    v_consumo := v_detalle.cantidad * v_factor;
    v_costo := coalesce(v_detalle.costo_unitario, 0);

    insert into public.ordenes_produccion_detalle (
      orden_id, tipo, insumo_id, cantidad, costo_unitario
    ) values (
      v_orden_id, 'consumo_insumo', v_detalle.insumo_id, v_consumo, v_costo
    );

    perform public.registrar_movimiento_inventario(
      'insumo',
      v_detalle.insumo_id,
      'produccion_salida',
      v_consumo,
      v_costo,
      'produccion',
      v_orden_id::text,
      coalesce(p_nota, 'Consumo de insumo en producción'),
      p_cajero,
      p_cajero_id
    );
  end loop;

  insert into public.ordenes_produccion_detalle (
    orden_id, tipo, producto_id, cantidad, costo_unitario
  ) values (
    v_orden_id, 'producto_terminado', p_producto_id, p_cantidad, 0
  );

  perform public.registrar_movimiento_inventario(
    'producto',
    p_producto_id,
    'produccion_entrada',
    p_cantidad,
    0,
    'produccion',
    v_orden_id::text,
    coalesce(p_nota, 'Ingreso por producción'),
    p_cajero,
    p_cajero_id
  );

  insert into public.inventario_config_productos (producto_id, controla_inventario, modo_consumo)
  values (p_producto_id, true, 'receta')
  on conflict (producto_id)
  do update set controla_inventario = true,
                modo_consumo = 'receta',
                updated_at = now();

  return v_orden_id;
end;
$$;

-- ============================================================================
-- 6) TRIGGER DE FACTURAS: CONTABILIDAD AUTOMÁTICA DE SALIDA POR VENTA
--    Lee NEW.productos (json string) y aplica la salida correcta.
--    NUNCA bloquea una venta — todos los errores de inventario se logean
--    como RAISE NOTICE y se continúa.
-- ============================================================================

create or replace function public.procesar_salida_inventario_por_venta()
returns trigger
language plpgsql
as $$
declare
  v_items       jsonb;
  v_item        jsonb;
  v_producto_id uuid;
  v_cantidad    numeric(14,4);
  v_nombre      text;
  v_tipo_pos    text;
  v_config      record;
  v_receta      record;
  v_detalle     record;
  v_consumo     numeric(14,4);
  v_ref_id      text;
begin
  v_ref_id := coalesce(new.factura, new.id::text);

  begin
    v_items := new.productos::jsonb;
  exception when others then
    raise notice 'inventario_venta: no se pudo parsear productos de factura %. Error: %',
                  v_ref_id, sqlerrm;
    return new;
  end;

  if jsonb_typeof(v_items) <> 'array' then
    return new;
  end if;

  for v_item in select * from jsonb_array_elements(v_items)
  loop
    begin  -- manejador por item: errores no bloquean la venta

      begin
        v_producto_id := coalesce(
          v_item ->> 'id',
          v_item ->> 'producto_id'
        )::uuid;
      exception when others then
        raise notice 'inventario_venta: UUID inválido en factura %, saltando item', v_ref_id;
        continue;
      end;

      v_cantidad := coalesce((v_item ->> 'cantidad')::numeric, 1);
      v_nombre   := coalesce(v_item ->> 'nombre', 'Producto');

      select p.tipo into v_tipo_pos
        from public.productos p
       where p.id = v_producto_id;

      select *
        into v_config
        from public.inventario_config_productos cfg
       where cfg.producto_id = v_producto_id;

      if not found then
        begin
          insert into public.inventario_config_productos (producto_id, controla_inventario, modo_consumo)
          values (
            v_producto_id,
            case when coalesce(v_tipo_pos,'') in ('comida','bebida','complemento') then true else false end,
            case
              when coalesce(v_tipo_pos,'') = 'comida'                   then 'receta'
              when coalesce(v_tipo_pos,'') in ('bebida','complemento')  then 'stock_producto'
              else 'sin_control'
            end
          )
          on conflict (producto_id) do nothing;
        exception when others then
          raise notice 'inventario_venta: no se pudo crear config para % — %', v_producto_id, sqlerrm;
        end;

        select *
          into v_config
          from public.inventario_config_productos cfg
         where cfg.producto_id = v_producto_id;
      end if;

      if coalesce(v_config.controla_inventario, false) = false
         or coalesce(v_config.modo_consumo, 'sin_control') = 'sin_control'
      then
        continue;
      end if;

      -- MODO: stock_producto (bebida, complemento)
      if v_config.modo_consumo = 'stock_producto' then
        begin
          perform public.registrar_movimiento_inventario(
            'producto', v_producto_id, 'venta', v_cantidad, 0,
            'factura', v_ref_id,
            'Salida automática por venta: ' || v_nombre,
            new.cajero, new.cajero_id::text,
            false  -- modo no estricto: no bloquear venta
          );
        exception when others then
          raise notice 'inventario_venta: error al descontar stock de producto % (factura %): %',
                        v_producto_id, v_ref_id, sqlerrm;
        end;

      -- MODO: receta (comida)
      elsif v_config.modo_consumo = 'receta' then

        select r.id, r.rendimiento
          into v_receta
          from public.recetas r
         where r.producto_id = v_producto_id
           and r.activo = true;

        if not found then
          raise notice 'inventario_venta: producto % vendido sin receta activa — no se descontó',
                        v_producto_id;
          continue;
        end if;

        for v_detalle in
          select rd.insumo_id, rd.cantidad,
                 coalesce(i.costo_unitario, 0) as costo_unitario
            from public.recetas_detalle rd
            join public.insumos i on i.id = rd.insumo_id
           where rd.receta_id = v_receta.id
        loop
          v_consumo := (v_detalle.cantidad / greatest(v_receta.rendimiento, 1)) * v_cantidad;
          begin
            perform public.registrar_movimiento_inventario(
              'insumo', v_detalle.insumo_id, 'venta', v_consumo, v_detalle.costo_unitario,
              'factura', v_ref_id,
              'Consumo automático por venta: ' || v_nombre,
              new.cajero, new.cajero_id::text,
              false  -- modo no estricto
            );
          exception when others then
            raise notice 'inventario_venta: error al descontar insumo % (factura %): %',
                          v_detalle.insumo_id, v_ref_id, sqlerrm;
          end;
        end loop;

      end if;

    exception when others then
      raise notice 'inventario_venta: error inesperado en factura % para producto %: %',
                    v_ref_id, coalesce(v_producto_id::text,'?'), sqlerrm;
    end;
  end loop;

  return new;
end;
$$;

drop trigger if exists trg_facturas_salida_inventario on public.facturas;
create trigger trg_facturas_salida_inventario
after insert on public.facturas
for each row execute function public.procesar_salida_inventario_por_venta();

-- ============================================================================
-- 7) VISTAS DE REPORTE
-- ============================================================================

create or replace view public.v_inventario_resumen as
select
  i.id,
  'insumo'::text as tipo_item,
  i.nombre,
  i.categoria,
  i.unidad,
  i.stock_actual,
  i.stock_minimo,
  i.costo_unitario,
  round(i.stock_actual * i.costo_unitario, 4) as valor_total,
  (i.stock_actual <= i.stock_minimo) as alerta_stock_bajo
from public.insumos i
where i.activo = true

union all

select
  sp.id,
  'producto'::text as tipo_item,
  p.nombre,
  p.tipo as categoria,
  'unidad'::text as unidad,
  sp.stock_actual,
  sp.stock_minimo,
  sp.costo_promedio as costo_unitario,
  round(sp.stock_actual * sp.costo_promedio, 4) as valor_total,
  (sp.stock_actual <= sp.stock_minimo) as alerta_stock_bajo
from public.stock_productos sp
join public.productos p on p.id = sp.producto_id
where sp.activo = true;

create or replace view public.v_recetas_resumen as
select
  r.id,
  r.producto_id,
  p.nombre as producto,
  p.tipo as categoria_producto,
  r.rendimiento,
  count(rd.id) as cantidad_insumos,
  r.activo,
  r.updated_at
from public.recetas r
join public.productos p on p.id = r.producto_id
left join public.recetas_detalle rd on rd.receta_id = r.id
group by r.id, r.producto_id, p.nombre, p.tipo, r.rendimiento, r.activo, r.updated_at;

-- ============================================================================
-- 8) RLS ABIERTA (SIGUIENDO EL PATRÓN ACTUAL DEL PROYECTO)
-- ============================================================================

alter table public.insumos enable row level security;
alter table public.stock_productos enable row level security;
alter table public.inventario_config_productos enable row level security;
alter table public.recetas enable row level security;
alter table public.recetas_detalle enable row level security;
alter table public.ordenes_produccion enable row level security;
alter table public.ordenes_produccion_detalle enable row level security;
alter table public.movimientos_inventario enable row level security;

do $$
declare
  t text;
  tables text[] := array[
    'insumos',
    'stock_productos',
    'inventario_config_productos',
    'recetas',
    'recetas_detalle',
    'ordenes_produccion',
    'ordenes_produccion_detalle',
    'movimientos_inventario'
  ];
begin
  foreach t in array tables
  loop
    if not exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = t
        and policyname = 'full_access_' || t
    ) then
      execute format(
        'create policy %I on public.%I for all to public using (true) with check (true)',
        'full_access_' || t,
        t
      );
    end if;
  end loop;
end $$;

-- ============================================================================
-- 9) DATOS INICIALES RECOMENDADOS
-- ============================================================================
-- Para comidas preparadas: configura modo_consumo = 'receta'
-- Para bebidas/complementos empacados: configura modo_consumo = 'stock_producto'
-- Para productos sin control: configura modo_consumo = 'sin_control'
--
-- Ejemplo opcional:
-- insert into public.inventario_config_productos (producto_id, controla_inventario, modo_consumo)
-- values ('UUID_DEL_PRODUCTO', true, 'stock_producto')
-- on conflict (producto_id) do update set modo_consumo = excluded.modo_consumo;
-- ============================================================================
